package com.lambda.client.util

import com.google.common.collect.ImmutableMap
import net.minecraft.block.Block
import net.minecraft.init.Biomes
import net.minecraft.init.Blocks
import net.minecraft.world.biome.Biome

/**
 * "ungenerate" different blocks to compare them with the seed.
 * @see [wiki/Random_patch](https://minecraft.fandom.com/wiki/Random_patch)
 */
class SeedOverlayBlockMap constructor(private val dimension: Int, biome: Biome = Biomes.PLAINS) {
    private var map: Map<Block, Int>

    init {
        map = biomeMap[biome]!!
    }

    fun setBiome(biome: Biome) {
        map = biomeMap[biome]!!
    }

    operator fun get(block: Block): Int {
        return map[block]
            ?: return if (dimension == 0) {
                overworld[block] ?: -1
            } else if (dimension == -1) {
                nether[block] ?: -1
            } else {
                end[block] ?: -1
            }
    }

    companion object {
        private val AIR_ID = Block.getIdFromBlock(Blocks.AIR)
        private val STONE_ID = Block.getIdFromBlock(Blocks.STONE)
        private val END_STONE_ID = Block.getIdFromBlock(Blocks.END_STONE)
        private val NETHERRACK_ID = Block.getIdFromBlock(Blocks.NETHERRACK)
        private val WATER_ID = Block.getIdFromBlock(Blocks.WATER)
        private val LAVA_ID = Block.getIdFromBlock(Blocks.LAVA)
        private val biomeMap: Map<Biome, Map<Block, Int>> = ImmutableMap.builder<Biome, Map<Block, Int>>()
            .put(
                Biomes.OCEAN, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.WATER, WATER_ID)
                    .put(Blocks.GRAVEL, STONE_ID)
                    .put(Blocks.SAND, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.CLAY, STONE_ID)
                    .put(Blocks.BROWN_MUSHROOM, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.PLAINS, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.STONE, STONE_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.SAND, AIR_ID)
                    .put(Blocks.CLAY, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.DESERT, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.SAND, STONE_ID)
                    .put(Blocks.SANDSTONE, STONE_ID)
                    .put(Blocks.CACTUS, AIR_ID)
                    .put(Blocks.DEADBUSH, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.EXTREME_HILLS, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.STONE, STONE_ID)
                    .put(Blocks.MONSTER_EGG, STONE_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .put(Blocks.SNOW, AIR_ID)
                    .put(Blocks.ICE, STONE_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .build()
            ).put(
                Biomes.FOREST, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.TAIGA, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.SWAMPLAND, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.WATER, WATER_ID)
                    .put(Blocks.WATERLILY, AIR_ID)
                    .put(Blocks.CLAY, STONE_ID)
                    .put(Blocks.VINE, AIR_ID)
                    .put(Blocks.RED_MUSHROOM, AIR_ID)
                    .put(Blocks.BROWN_MUSHROOM, AIR_ID)
                    .put(Blocks.DEADBUSH, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.RIVER, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.WATER, WATER_ID)
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.CLAY, STONE_ID)
                    .put(Blocks.SAND, STONE_ID)
                    .put(Blocks.GRAVEL, STONE_ID)
                    .put(Blocks.REEDS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.HELL, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.NETHERRACK, NETHERRACK_ID)
                    .put(Blocks.GLOWSTONE, AIR_ID)
                    .put(Blocks.SOUL_SAND, NETHERRACK_ID)
                    .put(Blocks.QUARTZ_ORE, NETHERRACK_ID)
                    .put(Blocks.GOLD_ORE, NETHERRACK_ID)
                    .put(Blocks.MAGMA, NETHERRACK_ID)
                    .put(Blocks.LAVA, LAVA_ID)
                    .put(Blocks.GRAVEL, NETHERRACK_ID)
                    .put(Blocks.RED_MUSHROOM, AIR_ID)
                    .put(Blocks.BROWN_MUSHROOM, AIR_ID)
                    .put(Blocks.FIRE, AIR_ID)
                    .build()
            ).put(
                Biomes.SKY, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.END_STONE, END_STONE_ID)
                    .put(Blocks.OBSIDIAN, AIR_ID)
                    .put(Blocks.BEDROCK, AIR_ID)
                    .build()
            ).put(
                Biomes.FROZEN_OCEAN, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.WATER, WATER_ID)
                    .put(Blocks.ICE, STONE_ID)
                    .put(Blocks.SNOW, STONE_ID)
                    .put(Blocks.PACKED_ICE, STONE_ID)
                    .put(Blocks.SNOW_LAYER, STONE_ID)
                    .put(Blocks.GRAVEL, STONE_ID)
                    .put(Blocks.SAND, STONE_ID)
                    .put(Blocks.CLAY, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.FROZEN_RIVER, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.ICE, STONE_ID)
                    .put(Blocks.WATER, WATER_ID)
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.CLAY, STONE_ID)
                    .put(Blocks.SAND, STONE_ID)
                    .put(Blocks.GRAVEL, STONE_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.ICE_PLAINS, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.SNOW, AIR_ID)
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.ICE, STONE_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.ICE_MOUNTAINS, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.SNOW, AIR_ID)
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.ICE, STONE_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUSHROOM_ISLAND, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.MYCELIUM, STONE_ID)
                    .put(Blocks.RED_MUSHROOM_BLOCK, AIR_ID)
                    .put(Blocks.BROWN_MUSHROOM_BLOCK, AIR_ID)
                    .put(Blocks.RED_MUSHROOM, AIR_ID)
                    .put(Blocks.BROWN_MUSHROOM, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUSHROOM_ISLAND_SHORE, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.MYCELIUM, STONE_ID)
                    .put(Blocks.RED_MUSHROOM_BLOCK, AIR_ID)
                    .put(Blocks.BROWN_MUSHROOM_BLOCK, AIR_ID)
                    .put(Blocks.RED_MUSHROOM, AIR_ID)
                    .put(Blocks.BROWN_MUSHROOM, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.BEACH, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.WATER, WATER_ID)
                    .put(Blocks.SAND, STONE_ID)
                    .put(Blocks.SANDSTONE, STONE_ID)
                    .put(Blocks.GRAVEL, STONE_ID)
                    .put(Blocks.CLAY, STONE_ID)
                    .put(Blocks.REEDS, AIR_ID)
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.DESERT_HILLS, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.SAND, STONE_ID)
                    .put(Blocks.SANDSTONE, STONE_ID)
                    .put(Blocks.CACTUS, AIR_ID)
                    .put(Blocks.DEADBUSH, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.FOREST_HILLS, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.TAIGA_HILLS, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.EXTREME_HILLS_EDGE, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.STONE, STONE_ID)
                    .put(Blocks.MONSTER_EGG, STONE_ID)
                    .put(Blocks.SNOW, AIR_ID)
                    .put(Blocks.ICE, STONE_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.JUNGLE, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.VINE, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.COCOA, AIR_ID)
                    .put(Blocks.MELON_BLOCK, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.JUNGLE_HILLS, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.VINE, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.COCOA, AIR_ID)
                    .put(Blocks.MELON_BLOCK, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.JUNGLE_EDGE, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.VINE, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.COCOA, AIR_ID)
                    .put(Blocks.MELON_BLOCK, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.DEEP_OCEAN, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.WATER, WATER_ID)
                    .put(Blocks.GRAVEL, STONE_ID)
                    .put(Blocks.MAGMA, STONE_ID)
                    .put(Blocks.OBSIDIAN, STONE_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.STONE_BEACH, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.WATER, WATER_ID)
                    .put(Blocks.STONE, STONE_ID)
                    .put(Blocks.GRAVEL, STONE_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.COLD_BEACH, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.WATER, WATER_ID)
                    .put(Blocks.SNOW, AIR_ID)
                    .put(Blocks.ICE, STONE_ID)
                    .put(Blocks.SAND, STONE_ID)
                    .put(Blocks.SANDSTONE, STONE_ID)
                    .put(Blocks.GRAVEL, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.CLAY, STONE_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.BIRCH_FOREST, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.BIRCH_FOREST_HILLS, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.ROOFED_FOREST, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.RED_MUSHROOM_BLOCK, AIR_ID)
                    .put(Blocks.BROWN_MUSHROOM_BLOCK, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.COLD_TAIGA, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.SNOW, AIR_ID)
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.ICE, STONE_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.COLD_TAIGA_HILLS, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.SNOW, AIR_ID)
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.ICE, STONE_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.REDWOOD_TAIGA, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.RED_MUSHROOM, AIR_ID)
                    .put(Blocks.BROWN_MUSHROOM, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.REDWOOD_TAIGA_HILLS, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.RED_MUSHROOM, AIR_ID)
                    .put(Blocks.BROWN_MUSHROOM, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.EXTREME_HILLS_WITH_TREES, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.STONE, STONE_ID)
                    .put(Blocks.SNOW, AIR_ID)
                    .put(Blocks.ICE, STONE_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.SAVANNA, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.SAVANNA_PLATEAU, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MESA, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.SAND, STONE_ID)
                    .put(Blocks.HARDENED_CLAY, STONE_ID)
                    .put(Blocks.STAINED_HARDENED_CLAY, STONE_ID)
                    .put(Blocks.CACTUS, AIR_ID)
                    .put(Blocks.DEADBUSH, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MESA_ROCK, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.SAND, STONE_ID)
                    .put(Blocks.HARDENED_CLAY, STONE_ID)
                    .put(Blocks.STAINED_HARDENED_CLAY, STONE_ID)
                    .put(Blocks.CACTUS, AIR_ID)
                    .put(Blocks.DEADBUSH, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .build()
            ).put(
                Biomes.MESA_CLEAR_ROCK, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.SAND, STONE_ID)
                    .put(Blocks.HARDENED_CLAY, STONE_ID)
                    .put(Blocks.STAINED_HARDENED_CLAY, STONE_ID)
                    .put(Blocks.CACTUS, AIR_ID)
                    .put(Blocks.DEADBUSH, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.VOID, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.COBBLESTONE, STONE_ID)
                    .put(Blocks.STONE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUTATED_PLAINS, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUTATED_DESERT, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.SAND, STONE_ID)
                    .put(Blocks.SANDSTONE, STONE_ID)
                    .put(Blocks.CACTUS, AIR_ID)
                    .put(Blocks.DEADBUSH, AIR_ID)
                    .put(Blocks.WATER, WATER_ID)
                    .put(Blocks.REEDS, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUTATED_EXTREME_HILLS, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRAVEL, STONE_ID)
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.SNOW, AIR_ID)
                    .put(Blocks.STONE, STONE_ID)
                    .put(Blocks.MONSTER_EGG, STONE_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUTATED_FOREST, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUTATED_TAIGA, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUTATED_SWAMPLAND, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.WATER, WATER_ID)
                    .put(Blocks.WATERLILY, AIR_ID)
                    .put(Blocks.CLAY, STONE_ID)
                    .put(Blocks.VINE, AIR_ID)
                    .put(Blocks.RED_MUSHROOM, AIR_ID)
                    .put(Blocks.BROWN_MUSHROOM, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUTATED_ICE_FLATS, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.PACKED_ICE, AIR_ID)
                    .put(Blocks.SNOW_LAYER, STONE_ID)
                    .put(Blocks.SNOW, AIR_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.ICE, STONE_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUTATED_JUNGLE, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.VINE, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.COCOA, AIR_ID)
                    .put(Blocks.MELON_BLOCK, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUTATED_JUNGLE_EDGE, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.VINE, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.COCOA, AIR_ID)
                    .put(Blocks.MELON_BLOCK, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUTATED_BIRCH_FOREST, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUTATED_BIRCH_FOREST_HILLS, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUTATED_ROOFED_FOREST, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.RED_MUSHROOM_BLOCK, AIR_ID)
                    .put(Blocks.BROWN_MUSHROOM_BLOCK, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUTATED_TAIGA_COLD, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRAVEL, STONE_ID)
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.SNOW_LAYER, AIR_ID)
                    .put(Blocks.SNOW, AIR_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUTATED_REDWOOD_TAIGA, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.RED_MUSHROOM, AIR_ID)
                    .put(Blocks.BROWN_MUSHROOM, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUTATED_REDWOOD_TAIGA_HILLS, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.RED_FLOWER, AIR_ID)
                    .put(Blocks.DOUBLE_PLANT, AIR_ID)
                    .put(Blocks.YELLOW_FLOWER, AIR_ID)
                    .put(Blocks.RED_MUSHROOM, AIR_ID)
                    .put(Blocks.BROWN_MUSHROOM, AIR_ID)
                    .put(Blocks.MOSSY_COBBLESTONE, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUTATED_EXTREME_HILLS_WITH_TREES, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRAVEL, STONE_ID)
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.SNOW, AIR_ID)
                    .put(Blocks.STONE, STONE_ID)
                    .put(Blocks.MONSTER_EGG, STONE_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUTATED_SAVANNA, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.STONE, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUTATED_SAVANNA_ROCK, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.STONE, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUTATED_MESA, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.SAND, STONE_ID)
                    .put(Blocks.HARDENED_CLAY, STONE_ID)
                    .put(Blocks.STAINED_HARDENED_CLAY, STONE_ID)
                    .put(Blocks.CACTUS, AIR_ID)
                    .put(Blocks.DEADBUSH, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            ).put(
                Biomes.MUTATED_MESA_ROCK, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.SAND, STONE_ID)
                    .put(Blocks.HARDENED_CLAY, STONE_ID)
                    .put(Blocks.STAINED_HARDENED_CLAY, STONE_ID)
                    .put(Blocks.CACTUS, AIR_ID)
                    .put(Blocks.DEADBUSH, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .put(Blocks.GRASS, STONE_ID)
                    .put(Blocks.DIRT, STONE_ID)
                    .put(Blocks.STONE, STONE_ID)
                    .put(Blocks.TALLGRASS, AIR_ID)
                    .put(Blocks.LOG, AIR_ID)
                    .put(Blocks.LOG2, AIR_ID)
                    .put(Blocks.LEAVES, AIR_ID)
                    .put(Blocks.LEAVES2, AIR_ID)
                    .build()
            ).put(
                Biomes.MUTATED_MESA_CLEAR_ROCK, ImmutableMap.builder<Block, Int>()
                    .put(Blocks.SAND, STONE_ID)
                    .put(Blocks.HARDENED_CLAY, STONE_ID)
                    .put(Blocks.STAINED_HARDENED_CLAY, STONE_ID)
                    .put(Blocks.CACTUS, AIR_ID)
                    .put(Blocks.DEADBUSH, AIR_ID)
                    .put(Blocks.EMERALD_ORE, STONE_ID)
                    .put(Blocks.COAL_ORE, STONE_ID)
                    .put(Blocks.IRON_ORE, STONE_ID)
                    .put(Blocks.GOLD_ORE, STONE_ID)
                    .put(Blocks.DIAMOND_ORE, STONE_ID)
                    .build()
            )
            .build()
        private val overworld: Map<Block, Int> = ImmutableMap.builder<Block, Int>()
            .put(Blocks.AIR, AIR_ID)
            .put(Blocks.BEDROCK, STONE_ID)
            .put(Blocks.STONE, STONE_ID)
            .put(Blocks.DIRT, STONE_ID)
            .put(Blocks.WATER, STONE_ID)
            .put(Blocks.FLOWING_WATER, STONE_ID)
            .put(Blocks.LAVA, STONE_ID)
            .put(Blocks.FLOWING_LAVA, STONE_ID)
            .put(Blocks.COAL_ORE, STONE_ID)
            .put(Blocks.IRON_ORE, STONE_ID)
            .put(Blocks.GOLD_ORE, STONE_ID)
            .put(Blocks.DIAMOND_ORE, STONE_ID)
            .put(Blocks.EMERALD_ORE, STONE_ID)
            .put(Blocks.LAPIS_ORE, STONE_ID)
            .put(Blocks.REDSTONE_ORE, STONE_ID)
            .put(Blocks.GRAVEL, STONE_ID)
            .build()
        private val nether: Map<Block, Int> = ImmutableMap.builder<Block, Int>()
            .put(Blocks.AIR, AIR_ID)
            .put(Blocks.BEDROCK, NETHERRACK_ID)
            .put(Blocks.NETHERRACK, NETHERRACK_ID)
            .put(Blocks.LAVA, STONE_ID)
            .put(Blocks.FLOWING_LAVA, STONE_ID)
            .put(Blocks.QUARTZ_ORE, NETHERRACK_ID)
            .put(Blocks.GOLD_ORE, NETHERRACK_ID)
            .build()
        private val end: Map<Block, Int> = ImmutableMap.builder<Block, Int>()
            .put(Blocks.AIR, AIR_ID)
            .put(Blocks.END_STONE, END_STONE_ID)
            .put(Blocks.CHORUS_FLOWER, AIR_ID)
            .put(Blocks.CHORUS_PLANT, AIR_ID)
            .build()
    }
}